---
version: "2"
plugins:
  duplication:
    enabled: true
    config:
      languages:
      - php
  fixme:
    enabled: true
  markdownlint:
    enabled: true
  phpcodesniffer:
    enabled: true
    config:
      standard: "WordPress-Core,WordPress-Docs,WordPress-Extra"
  phpmd:
    enabled: true
    checks:
      Controversial/CamelCaseMethodName:
        enabled: false
      Controversial/CamelCaseParameterName:
        enabled: false
      Controversial/CamelCasePropertyName:
        enabled: false
      Controversial/CamelCaseVariableName:
        enabled: false
      CleanCode/ElseExpression:
        enabled: false
exclude_patterns:
  - "**.dist"
  - "**.lock"
  - "**.json"
  - "**.sh"
  - "**.txt"
  - "tests/*"
  - "vendor/**"
